spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.237.128:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 20001

logging:
  level:
    com.com.example.gulimall: debug

